apiVersion: v1
kind: ConfigMap
metadata:
  name: meilisearch-env
data:
  meili_env: production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-env
data:
  allow_empty_password: yes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: barassistant-env
data:
  app_url: http://bar.nas.dogeek.me
  log_channel: stderr
  meilisearch_host: http://meilisearch.ix-bar-assistant.svc.cluster.local:7700
  redis_host: http://redis.ix-bar-assistant.svc.cluster.local:6379
  allow_registration: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: saltrim-env
data:
  api_url: http://bar-assistant.ix-bar-assistant.svc.cluster.local:8080
  meilisearch_url: http://meilisearch.ix-bar-assistant.svc.cluster.local:7700
  bar_name: Bar
  description: Home bar
  default_locale: en-US
